spring.application.name=RPG_Manager2.0

# Spring Boot 4.x - Remove o stack trace
server.error.include-stacktrace=never

# Spring Boot 4.x - Remove binding errors
server.error.include-binding-errors=never

# Desabilita o trace completamente
spring.mvc.log-resolved-exception=false

# Resposta de erro minimalista
server.error.whitelabel.enabled=false

