spring.application.name=RPG_Manager2.0

# Spring Boot 4.x - Remove o stack trace
server.error.include-stacktrace=never

# Spring Boot 4.x - Remove binding errors
server.error.include-binding-errors=never

# Desabilita o trace completamente
spring.mvc.log-resolved-exception=false

# Resposta de erro minimalista
server.error.whitelabel.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
